//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "retreat_room_types")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub retreat_room_type_id: i64,
    pub retreat_id: i64,
    pub name: String,
    pub slug: String,
    pub description: Option<String>,
    pub size_sqm: Option<i32>,
    pub max_guests: Option<i32>,
    pub bed_configuration: Option<String>,
    pub amenities: Option<String>,
    pub price_per_night: Option<Decimal>,
    pub is_featured: bool,
    pub image_path: Option<String>,
    pub display_order: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub created_by: Option<i64>,
    pub updated_by: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::retreat_packages::Entity")]
    RetreatPackages,
    #[sea_orm(
        belongs_to = "super::retreats::Entity",
        from = "Column::RetreatId",
        to = "super::retreats::Column::RetreatId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Retreats,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatedBy",
        to = "super::users::Column::UserId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UpdatedBy",
        to = "super::users::Column::UserId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users1,
}

impl Related<super::retreat_packages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RetreatPackages.def()
    }
}

impl Related<super::retreats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Retreats.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
