//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "retreat_amenities")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub retreat_amenities_id: i64,
    pub retreat_id: i64,
    pub amenity_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::amenities::Entity",
        from = "Column::AmenityId",
        to = "super::amenities::Column::AmenityId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Amenities,
    #[sea_orm(
        belongs_to = "super::retreats::Entity",
        from = "Column::RetreatId",
        to = "super::retreats::Column::RetreatId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Retreats,
}

impl Related<super::amenities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Amenities.def()
    }
}

impl Related<super::retreats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Retreats.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
