//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub user_id: i64,
    pub name: String,
    #[sea_orm(unique)]
    pub email: String,
    pub password: String,
    pub phone: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::admin_users::Entity")]
    AdminUsers,
    #[sea_orm(has_many = "super::password_reset_tokens::Entity")]
    PasswordResetTokens,
    #[sea_orm(has_many = "super::retreat_reviews::Entity")]
    RetreatReviews,
    #[sea_orm(has_many = "super::wishlists::Entity")]
    Wishlists,
}

impl Related<super::admin_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AdminUsers.def()
    }
}

impl Related<super::password_reset_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PasswordResetTokens.def()
    }
}

impl Related<super::retreat_reviews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RetreatReviews.def()
    }
}

impl Related<super::wishlists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Wishlists.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
